image: 
  file: .gitpod.dockerfile

tasks:
  - name: Init project
    init: |
      python3 -m venv .venv
      . .venv/bin/activate
      # upgrade some dependencies
      pip install --upgrade pip wheel setuptools
      pip install -r requirements.txt
      echo "gitpod workspace initiated"
  - name: Command
    command: |
      . .venv/bin/activate
      echo "Welcome to your gitpod workspace with venv!"

vscode:
  extensions:
    - ms-python.python
    - ms-python.debugpy
